/* tslint:disable */
/* eslint-disable */
/**
 * Fabric CA Server API
 * Hyperledger Fabric CA Server APIs provides certificate authority services for the blockchain.
 *
 * OpenAPI spec version: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Body6
 */
export interface Body6 {
    /**
     * The enrollment ID which uniquely identifies an identity
     * @type {string}
     * @memberof Body6
     */
    id: any;
    /**
     * The type of the identity (e.g. *user*, *app*, *peer*, *orderer*, etc)
     * @type {string}
     * @memberof Body6
     */
    type?: any;
    /**
     * The affiliation path of the new identity. 
     * @type {string}
     * @memberof Body6
     */
    affiliation: any;
    /**
     * An array of attribute names and values to give to the new identity.
     * @type {Array&lt;Apiv1registerAttrs&gt;}
     * @memberof Body6
     */
    attrs: any;
}
