/* tslint:disable */
/* eslint-disable */
/**
 * Fabric CA Server API
 * Hyperledger Fabric CA Server APIs provides certificate authority services for the blockchain.
 *
 * OpenAPI spec version: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Body1
 */
export interface Body1 {
    /**
     * JSON encoding idemix.CredentialRequest struct
     * @type {string}
     * @memberof Body1
     */
    request: any;
    /**
     * Name of the CA to direct this request to within the Fabric CA server
     * @type {string}
     * @memberof Body1
     */
    caname?: any;
}
