/* tslint:disable */
/* eslint-disable */
/**
 * Fabric CA Server API
 * Hyperledger Fabric CA Server APIs provides certificate authority services for the blockchain.
 *
 * OpenAPI spec version: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse2012
 */
export interface InlineResponse2012 {
    /**
     * Boolean indicating if the request was successful.
     * @type {boolean}
     * @memberof InlineResponse2012
     */
    success: any;
    /**
     * 
     * @type {InlineResponse2012Result}
     * @memberof InlineResponse2012
     */
    result: any;
    /**
     * An array of error messages (code and message)
     * @type {Array&lt;InlineResponse200Errors&gt;}
     * @memberof InlineResponse2012
     */
    errors: any;
    /**
     * An array of information messages (code and message)
     * @type {Array&lt;InlineResponse200Messages&gt;}
     * @memberof InlineResponse2012
     */
    messages: any;
}
