/* tslint:disable */
/* eslint-disable */
/**
 * Fabric CA Server API
 * Hyperledger Fabric CA Server APIs provides certificate authority services for the blockchain.
 *
 * OpenAPI spec version: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AffiliationInfo
 */
export interface AffiliationInfo {
    /**
     * The affiliation path
     * @type {string}
     * @memberof AffiliationInfo
     */
    name?: any;
    /**
     * 
     * @type {Array&lt;AffiliationInfo&gt;}
     * @memberof AffiliationInfo
     */
    affiliations?: any;
    /**
     * 
     * @type {Array&lt;IdentityInfo&gt;}
     * @memberof AffiliationInfo
     */
    identities?: any;
}
