/* tslint:disable */
/* eslint-disable */
/**
 * Fabric CA Server API
 * Hyperledger Fabric CA Server APIs provides certificate authority services for the blockchain.
 *
 * OpenAPI spec version: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Apiv1enrollAttrReqs
 */
export interface Apiv1enrollAttrReqs {
    /**
     * The name of the attribute being requested to put into the enrollment certificate.
     * @type {string}
     * @memberof Apiv1enrollAttrReqs
     */
    name: any;
    /**
     * Boolean indicating whether the attribute is optional. An error is returned if the attribute is required but not found. The default value is false.
     * @type {boolean}
     * @memberof Apiv1enrollAttrReqs
     */
    optional?: any;
}
