/* tslint:disable */
/* eslint-disable */
/**
 * Fabric CA Server API
 * Hyperledger Fabric CA Server APIs provides certificate authority services for the blockchain.
 *
 * OpenAPI spec version: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Apiv1registerAttrs
 */
export interface Apiv1registerAttrs {
    /**
     * Attribute name
     * @type {string}
     * @memberof Apiv1registerAttrs
     */
    name: any;
    /**
     * Value of attribute
     * @type {string}
     * @memberof Apiv1registerAttrs
     */
    value: any;
    /**
     * A value of true indicates that this attribute should be included in an enrollment certificate by default
     * @type {boolean}
     * @memberof Apiv1registerAttrs
     */
    ecert?: any;
}
