/* tslint:disable */
/* eslint-disable */
/**
 * Fabric CA Server API
 * Hyperledger Fabric CA Server APIs provides certificate authority services for the blockchain.
 *
 * OpenAPI spec version: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Body3
 */
export interface Body3 {
    /**
     * The enrollment ID which uniquely identifies an identity
     * @type {string}
     * @memberof Body3
     */
    id: any;
    /**
     * The type of the identity (e.g. *user*, *app*, *peer*, *orderer*, etc)
     * @type {string}
     * @memberof Body3
     */
    type?: any;
    /**
     * The affiliation of the new identity.  If no affliation is provided, the affiliation of the registrar is used.
     * @type {string}
     * @memberof Body3
     */
    affiliation?: any;
    /**
     * An array of attribute names and values to give to the registered identity.
     * @type {Array&lt;Apiv1registerAttrs&gt;}
     * @memberof Body3
     */
    attrs: any;
}
