/* tslint:disable */
/* eslint-disable */
/**
 * Fabric CA Server API
 * Hyperledger Fabric CA Server APIs provides certificate authority services for the blockchain.
 *
 * OpenAPI spec version: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Body7
 */
export interface Body7 {
    /**
     * The new type of the identity (e.g. *user*, *app*, *peer*, *orderer*, etc)
     * @type {string}
     * @memberof Body7
     */
    type?: any;
    /**
     * The affiliation path of the identity. 
     * @type {string}
     * @memberof Body7
     */
    affiliation?: any;
    /**
     * An array of attribute names and values to add or modify for the identity.  If the value is omitted, delete the attribute.
     * @type {Array&lt;Apiv1identitiesidAttrs&gt;}
     * @memberof Body7
     */
    attrs?: any;
}
