/* tslint:disable */
/* eslint-disable */
/**
 * Fabric CA Server API
 * Hyperledger Fabric CA Server APIs provides certificate authority services for the blockchain.
 *
 * OpenAPI spec version: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse2011
 */
export interface InlineResponse2011 {
    /**
     * Boolean indicating if the request was successful
     * @type {boolean}
     * @memberof InlineResponse2011
     */
    success: any;
    /**
     * 
     * @type {InlineResponse2011Result}
     * @memberof InlineResponse2011
     */
    result: any;
    /**
     * A array of error messages (i.e. code and string messages).
     * @type {Array&lt;InlineResponse200Errors&gt;}
     * @memberof InlineResponse2011
     */
    errors: any;
    /**
     * A array of informational messages (i.e. code and string messages).
     * @type {Array&lt;InlineResponse200Messages&gt;}
     * @memberof InlineResponse2011
     */
    messages: any;
}
